### ISSUE TITLE
repo access rights

### ISSUE THREAD

**Issue by paddibr** [stadt-bielefeld/bielefeldGEOCLIENT#31]
Hey,

super Projekt! Ich bin nach der Readme in /dev gegangen um es lokal ans laufen zu bekommen.

Das Repo unter Punkt "Clone, build (and watch) anol" ist nicht öffentlich. => git@github.com:terrestris/anol

Und muss ich Nodejs auf dem Rechner installieren? Nicht innerhalb des Containers?

**Comment by mrclBIE** [comment]
Hey @paddibr,

vielen Dank für Ihr Interesse an unserem Web-GIS Client. Die Software wird aktuell dockerisiert, weshalb sich die Installation in Kürze grundlegend ändern wird. Sobald dieses Update abgeschlossen ist, geben wir Ihnen gerne eine Rückmeldung.

Viele Grüße,
Marcel Tesch
Stadt Bielefeld | Amt für Geoinformation und Kataster

**Comment by simonseyock** [comment]
@paddibr abgesehen von dem angemerkten update ist das anol repository schon öffentlich. Sie finden es unter der URL https://github.com/terrestris/anol. Vielleicht können Sie es auf Grund lokaler Einstellungen nicht über ssh erreichen?
