### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by paddibr** [stadt-bielefeld/bielefeldGEOCLIENT#70]
Beim Build mit  `docker-compose --profile prod build` erhalte ich folgenden Fehler:

![docker_err](https://user-images.githubusercontent.com/9463756/228280387-2d22368c-6d0c-4fec-8615-fd2dd4d0c3ef.jpg)

Meine Recherche ergab, dass Debian jessie entfernt hat. Lässt sich das fixen?

**Comment by jansule** [comment]
Danke für die Info @paddibr. Ein Quickfix wäre, in https://github.com/stadt-bielefeld/bielefeldGEOCLIENT/blob/main/docker/munimap-mapproxy/build/Dockerfile#L1 auf eine aktuellere Debian Version zu gehen. Es kann natürlich sein, dass damit weitere Änderungen am Dockerfile nötig werden.

Auf lange Sicht sollte das offizielle MapProxy Image verwendet werden, das grade in der Mache ist (siehe https://github.com/mapproxy/mapproxy/pull/634)

**Comment by mrclBIE** [comment]
Ich habe einige weitere Python base images getestet: 

- python:2.7-alpine3.10
- python:3.9.10-slim-buster
- python:3.9.10-buster
- python:2.7.18-slim-buster

Leider ohne Erfolg.
